# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\widgets\metadata\edges.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\widgets\metadata\edges.ui' applies.
#
# Created: Sat Mar  5 14:43:09 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_EdgesWidget(object):
    def setupUi(self, EdgesWidget):
        EdgesWidget.setObjectName("EdgesWidget")
        EdgesWidget.resize(348, 300)
        EdgesWidget.setWindowTitle("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EdgesWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btHighlightSelectedEdges = QtWidgets.QToolButton(EdgesWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/highlight-red.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btHighlightSelectedEdges.setIcon(icon)
        self.btHighlightSelectedEdges.setIconSize(QtCore.QSize(24, 24))
        self.btHighlightSelectedEdges.setObjectName("btHighlightSelectedEdges")
        self.horizontalLayout.addWidget(self.btHighlightSelectedEdges)
        self.btHighlightNodesFromSelectedEdges = QtWidgets.QToolButton(EdgesWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/highlight-yellow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btHighlightNodesFromSelectedEdges.setIcon(icon1)
        self.btHighlightNodesFromSelectedEdges.setIconSize(QtCore.QSize(24, 24))
        self.btHighlightNodesFromSelectedEdges.setObjectName("btHighlightNodesFromSelectedEdges")
        self.horizontalLayout.addWidget(self.btHighlightNodesFromSelectedEdges)
        self.line = QtWidgets.QFrame(EdgesWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.btSetAlternatingRowColors = QtWidgets.QToolButton(EdgesWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/alternating_row_colors.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSetAlternatingRowColors.setIcon(icon2)
        self.btSetAlternatingRowColors.setIconSize(QtCore.QSize(24, 24))
        self.btSetAlternatingRowColors.setObjectName("btSetAlternatingRowColors")
        self.horizontalLayout.addWidget(self.btSetAlternatingRowColors)
        self.btEnableOrdering = QtWidgets.QToolButton(EdgesWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/enable_ordering.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btEnableOrdering.setIcon(icon3)
        self.btEnableOrdering.setIconSize(QtCore.QSize(24, 24))
        self.btEnableOrdering.setObjectName("btEnableOrdering")
        self.horizontalLayout.addWidget(self.btEnableOrdering)
        self.btSetColumnsMovable = QtWidgets.QToolButton(EdgesWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/enable_move_columns.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSetColumnsMovable.setIcon(icon4)
        self.btSetColumnsMovable.setIconSize(QtCore.QSize(24, 24))
        self.btSetColumnsMovable.setObjectName("btSetColumnsMovable")
        self.horizontalLayout.addWidget(self.btSetColumnsMovable)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tvEdges = EdgeTableView(EdgesWidget)
        self.tvEdges.setAlternatingRowColors(True)
        self.tvEdges.setObjectName("tvEdges")
        self.verticalLayout_2.addWidget(self.tvEdges)
        self.actionHighlightSelectedEdges = QtWidgets.QAction(EdgesWidget)
        self.actionHighlightSelectedEdges.setIcon(icon)
        self.actionHighlightSelectedEdges.setObjectName("actionHighlightSelectedEdges")
        self.actionHighlightNodesFromSelectedEdges = QtWidgets.QAction(EdgesWidget)
        self.actionHighlightNodesFromSelectedEdges.setIcon(icon1)
        self.actionHighlightNodesFromSelectedEdges.setObjectName("actionHighlightNodesFromSelectedEdges")
        self.actionSetAlternatingRowColors = QtWidgets.QAction(EdgesWidget)
        self.actionSetAlternatingRowColors.setCheckable(True)
        self.actionSetAlternatingRowColors.setChecked(True)
        self.actionSetAlternatingRowColors.setIcon(icon2)
        self.actionSetAlternatingRowColors.setObjectName("actionSetAlternatingRowColors")
        self.actionEnableOrdering = QtWidgets.QAction(EdgesWidget)
        self.actionEnableOrdering.setCheckable(True)
        self.actionEnableOrdering.setIcon(icon3)
        self.actionEnableOrdering.setObjectName("actionEnableOrdering")
        self.actionSetColumnsMovable = QtWidgets.QAction(EdgesWidget)
        self.actionSetColumnsMovable.setCheckable(True)
        self.actionSetColumnsMovable.setIcon(icon4)
        self.actionSetColumnsMovable.setObjectName("actionSetColumnsMovable")

        self.retranslateUi(EdgesWidget)
        QtCore.QMetaObject.connectSlotsByName(EdgesWidget)

    def retranslateUi(self, EdgesWidget):
        self.btHighlightSelectedEdges.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the selected edges in the table", None, -1))
        self.btHighlightSelectedEdges.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the selected edges in the table", None, -1))
        self.btHighlightSelectedEdges.setText(QtWidgets.QApplication.translate("EdgesWidget", "...", None, -1))
        self.btHighlightNodesFromSelectedEdges.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the nodes connected by selected edges in the table", None, -1))
        self.btHighlightNodesFromSelectedEdges.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the nodes connected by selected edges in the table", None, -1))
        self.btHighlightNodesFromSelectedEdges.setText(QtWidgets.QApplication.translate("EdgesWidget", "...", None, -1))
        self.btSetAlternatingRowColors.setText(QtWidgets.QApplication.translate("EdgesWidget", "...", None, -1))
        self.btEnableOrdering.setText(QtWidgets.QApplication.translate("EdgesWidget", "...", None, -1))
        self.btSetColumnsMovable.setText(QtWidgets.QApplication.translate("EdgesWidget", "...", None, -1))
        self.actionHighlightSelectedEdges.setText(QtWidgets.QApplication.translate("EdgesWidget", "Highlight Selected Edges", None, -1))
        self.actionHighlightSelectedEdges.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the selected edges in the table", None, -1))
        self.actionHighlightSelectedEdges.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the selected edges in the table", None, -1))
        self.actionHighlightNodesFromSelectedEdges.setText(QtWidgets.QApplication.translate("EdgesWidget", "Highlight nodes from selected edges", None, -1))
        self.actionHighlightNodesFromSelectedEdges.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the nodes connected by selected edges in the table", None, -1))
        self.actionHighlightNodesFromSelectedEdges.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Highlight in network views the nodes connected by selected edges in the table", None, -1))
        self.actionSetAlternatingRowColors.setText(QtWidgets.QApplication.translate("EdgesWidget", "Set Alternating Row Colors", None, -1))
        self.actionSetAlternatingRowColors.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Alternate background colors in table to improve readability", None, -1))
        self.actionSetAlternatingRowColors.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Alternate background colors in table to improve readability", None, -1))
        self.actionEnableOrdering.setText(QtWidgets.QApplication.translate("EdgesWidget", "Enable Ordering", None, -1))
        self.actionEnableOrdering.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Enable ordering of table. Selection of columns is available only when sorting is disabled", None, -1))
        self.actionEnableOrdering.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Enable ordering of table. Selection of columns is available only when sorting is disabled", None, -1))
        self.actionSetColumnsMovable.setText(QtWidgets.QApplication.translate("EdgesWidget", "Set Columns Movable", None, -1))
        self.actionSetColumnsMovable.setToolTip(QtWidgets.QApplication.translate("EdgesWidget", "Allow to change order of columns", None, -1))
        self.actionSetColumnsMovable.setStatusTip(QtWidgets.QApplication.translate("EdgesWidget", "Allow to change order of columns", None, -1))

from metgem_app.ui.widgets.metadata.edge import EdgeTableView
import ui_rc
