# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\widgets\databases_options_widget.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\widgets\databases_options_widget.ui' applies.
#
# Created: Sat Mar  5 14:43:02 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_gbDatabaseOptions(object):
    def setupUi(self, gbDatabaseOptions):
        gbDatabaseOptions.setObjectName("gbDatabaseOptions")
        gbDatabaseOptions.resize(230, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gbDatabaseOptions.sizePolicy().hasHeightForWidth())
        gbDatabaseOptions.setSizePolicy(sizePolicy)
        gbDatabaseOptions.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(gbDatabaseOptions)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(gbDatabaseOptions)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(gbDatabaseOptions)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gbAnalogs = QtWidgets.QGroupBox(gbDatabaseOptions)
        self.gbAnalogs.setEnabled(True)
        self.gbAnalogs.setFlat(True)
        self.gbAnalogs.setCheckable(True)
        self.gbAnalogs.setChecked(False)
        self.gbAnalogs.setObjectName("gbAnalogs")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbAnalogs)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.gbAnalogs)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinAnalogTolerance = QtWidgets.QDoubleSpinBox(self.gbAnalogs)
        self.spinAnalogTolerance.setPrefix("")
        self.spinAnalogTolerance.setSuffix("")
        self.spinAnalogTolerance.setDecimals(1)
        self.spinAnalogTolerance.setMinimum(1.0)
        self.spinAnalogTolerance.setMaximum(200.0)
        self.spinAnalogTolerance.setSingleStep(0.1)
        self.spinAnalogTolerance.setProperty("value", 100.0)
        self.spinAnalogTolerance.setObjectName("spinAnalogTolerance")
        self.horizontalLayout.addWidget(self.spinAnalogTolerance)
        self.gridLayout.addWidget(self.gbAnalogs, 8, 0, 1, 2)
        self.spinParentFilterTolerance = QtWidgets.QSpinBox(gbDatabaseOptions)
        self.spinParentFilterTolerance.setEnabled(True)
        self.spinParentFilterTolerance.setSuffix("")
        self.spinParentFilterTolerance.setMaximum(100)
        self.spinParentFilterTolerance.setProperty("value", 17)
        self.spinParentFilterTolerance.setObjectName("spinParentFilterTolerance")
        self.gridLayout.addWidget(self.spinParentFilterTolerance, 4, 1, 1, 1)
        self.spinMZTolerance = QtWidgets.QDoubleSpinBox(gbDatabaseOptions)
        self.spinMZTolerance.setEnabled(True)
        self.spinMZTolerance.setSuffix("")
        self.spinMZTolerance.setMaximum(100.0)
        self.spinMZTolerance.setSingleStep(0.01)
        self.spinMZTolerance.setProperty("value", 0.02)
        self.spinMZTolerance.setObjectName("spinMZTolerance")
        self.gridLayout.addWidget(self.spinMZTolerance, 1, 1, 1, 1)
        self.spinMinScore = QtWidgets.QDoubleSpinBox(gbDatabaseOptions)
        self.spinMinScore.setMaximum(1.0)
        self.spinMinScore.setSingleStep(0.05)
        self.spinMinScore.setProperty("value", 0.7)
        self.spinMinScore.setObjectName("spinMinScore")
        self.gridLayout.addWidget(self.spinMinScore, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(gbDatabaseOptions)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(gbDatabaseOptions)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.cbPolarity = QtWidgets.QComboBox(gbDatabaseOptions)
        self.cbPolarity.setMaxVisibleItems(2)
        self.cbPolarity.setMaxCount(2)
        self.cbPolarity.setObjectName("cbPolarity")
        self.gridLayout.addWidget(self.cbPolarity, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(gbDatabaseOptions)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinMinIntensity = QtWidgets.QSpinBox(gbDatabaseOptions)
        self.spinMinIntensity.setEnabled(True)
        self.spinMinIntensity.setMaximum(100)
        self.spinMinIntensity.setObjectName("spinMinIntensity")
        self.gridLayout.addWidget(self.spinMinIntensity, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(gbDatabaseOptions)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinMinMatchedPeaks = QtWidgets.QSpinBox(gbDatabaseOptions)
        self.spinMinMatchedPeaks.setEnabled(True)
        self.spinMinMatchedPeaks.setMaximum(100)
        self.spinMinMatchedPeaks.setProperty("value", 4)
        self.spinMinMatchedPeaks.setObjectName("spinMinMatchedPeaks")
        self.gridLayout.addWidget(self.spinMinMatchedPeaks, 2, 1, 1, 1)

        self.retranslateUi(gbDatabaseOptions)
        QtCore.QMetaObject.connectSlotsByName(gbDatabaseOptions)
        gbDatabaseOptions.setTabOrder(self.cbPolarity, self.spinMZTolerance)
        gbDatabaseOptions.setTabOrder(self.spinMZTolerance, self.spinMinIntensity)
        gbDatabaseOptions.setTabOrder(self.spinMinIntensity, self.spinParentFilterTolerance)
        gbDatabaseOptions.setTabOrder(self.spinParentFilterTolerance, self.spinMinScore)
        gbDatabaseOptions.setTabOrder(self.spinMinScore, self.gbAnalogs)
        gbDatabaseOptions.setTabOrder(self.gbAnalogs, self.spinAnalogTolerance)

    def retranslateUi(self, gbDatabaseOptions):
        gbDatabaseOptions.setToolTip(QtWidgets.QApplication.translate("gbDatabaseOptions", "Save databases selection", None, -1))
        gbDatabaseOptions.setStatusTip(QtWidgets.QApplication.translate("gbDatabaseOptions", "Save databases selection", None, -1))
        gbDatabaseOptions.setTitle(QtWidgets.QApplication.translate("gbDatabaseOptions", "Query Database", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "<i>m/z</i> parent Filter Tolerance", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "Minimal Intensity", None, -1))
        self.gbAnalogs.setTitle(QtWidgets.QApplication.translate("gbDatabaseOptions", "Search for analogs", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "<i>m/z</i> Tolerance", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "Minimal Cosine Score Value", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "<i>m/z</i> Tolerance", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "Polarity", None, -1))
        self.spinMinIntensity.setSuffix(QtWidgets.QApplication.translate("gbDatabaseOptions", "%", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("gbDatabaseOptions", "Minimum Matched Peaks", None, -1))

