# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\widgets\tsne_options_widget.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\widgets\tsne_options_widget.ui' applies.
#
# Created: Sat Mar  5 14:43:06 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_gbTSNEOptions(object):
    def setupUi(self, gbTSNEOptions):
        gbTSNEOptions.setObjectName("gbTSNEOptions")
        gbTSNEOptions.resize(331, 189)
        self.gridLayout_3 = QtWidgets.QGridLayout(gbTSNEOptions)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(gbTSNEOptions)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(gbTSNEOptions)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 2, 1, 1)
        self.spinTSNEPerplexity = QtWidgets.QSpinBox(gbTSNEOptions)
        self.spinTSNEPerplexity.setEnabled(True)
        self.spinTSNEPerplexity.setMinimum(5)
        self.spinTSNEPerplexity.setMaximum(50)
        self.spinTSNEPerplexity.setProperty("value", 6)
        self.spinTSNEPerplexity.setObjectName("spinTSNEPerplexity")
        self.gridLayout_3.addWidget(self.spinTSNEPerplexity, 3, 3, 1, 1)
        self.chkRandomState = QtWidgets.QCheckBox(gbTSNEOptions)
        self.chkRandomState.setObjectName("chkRandomState")
        self.gridLayout_3.addWidget(self.chkRandomState, 5, 0, 1, 5)
        self.spinTSNEEarlyExaggeration = QtWidgets.QSpinBox(gbTSNEOptions)
        self.spinTSNEEarlyExaggeration.setMaximum(100)
        self.spinTSNEEarlyExaggeration.setProperty("value", 12)
        self.spinTSNEEarlyExaggeration.setObjectName("spinTSNEEarlyExaggeration")
        self.gridLayout_3.addWidget(self.spinTSNEEarlyExaggeration, 4, 3, 1, 1)
        self.gbBarnesHut = QtWidgets.QGroupBox(gbTSNEOptions)
        self.gbBarnesHut.setCheckable(True)
        self.gbBarnesHut.setObjectName("gbBarnesHut")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbBarnesHut)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.gbBarnesHut)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinAngle = QtWidgets.QDoubleSpinBox(self.gbBarnesHut)
        self.spinAngle.setDecimals(1)
        self.spinAngle.setMaximum(1.0)
        self.spinAngle.setSingleStep(0.1)
        self.spinAngle.setProperty("value", 0.5)
        self.spinAngle.setObjectName("spinAngle")
        self.horizontalLayout.addWidget(self.spinAngle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.gbBarnesHut, 6, 0, 1, 5)
        self.spinTSNELearningRate = QtWidgets.QSpinBox(gbTSNEOptions)
        self.spinTSNELearningRate.setEnabled(True)
        self.spinTSNELearningRate.setMinimum(10)
        self.spinTSNELearningRate.setMaximum(1000)
        self.spinTSNELearningRate.setSingleStep(10)
        self.spinTSNELearningRate.setProperty("value", 200)
        self.spinTSNELearningRate.setObjectName("spinTSNELearningRate")
        self.gridLayout_3.addWidget(self.spinTSNELearningRate, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(gbTSNEOptions)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(gbTSNEOptions)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.spinNumIterations = QtWidgets.QSpinBox(gbTSNEOptions)
        self.spinNumIterations.setMinimum(250)
        self.spinNumIterations.setMaximum(10000)
        self.spinNumIterations.setSingleStep(250)
        self.spinNumIterations.setProperty("value", 1000)
        self.spinNumIterations.setObjectName("spinNumIterations")
        self.gridLayout_3.addWidget(self.spinNumIterations, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(gbTSNEOptions)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinMinScoresAboveThreshold = QtWidgets.QSpinBox(gbTSNEOptions)
        self.spinMinScoresAboveThreshold.setMinimum(1)
        self.spinMinScoresAboveThreshold.setMaximum(100)
        self.spinMinScoresAboveThreshold.setObjectName("spinMinScoresAboveThreshold")
        self.horizontalLayout_2.addWidget(self.spinMinScoresAboveThreshold)
        self.label_8 = QtWidgets.QLabel(gbTSNEOptions)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.spinMinScore = QtWidgets.QDoubleSpinBox(gbTSNEOptions)
        self.spinMinScore.setMaximum(1.0)
        self.spinMinScore.setSingleStep(0.05)
        self.spinMinScore.setProperty("value", 0.7)
        self.spinMinScore.setObjectName("spinMinScore")
        self.horizontalLayout_2.addWidget(self.spinMinScore)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)

        self.retranslateUi(gbTSNEOptions)
        QtCore.QMetaObject.connectSlotsByName(gbTSNEOptions)
        gbTSNEOptions.setTabOrder(self.spinMinScore, self.chkRandomState)
        gbTSNEOptions.setTabOrder(self.chkRandomState, self.gbBarnesHut)

    def retranslateUi(self, gbTSNEOptions):
        gbTSNEOptions.setTitle(QtWidgets.QApplication.translate("gbTSNEOptions", "t-SNE Visualization", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Number of iterations", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Perplexity", None, -1))
        self.chkRandomState.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Random Initial State", None, -1))
        self.gbBarnesHut.setTitle(QtWidgets.QApplication.translate("gbTSNEOptions", "Use Barnes-Hut approximation", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Angle", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Early exaggeration", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "Learning  Rate", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "At least", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("gbTSNEOptions", "cosine score(s) above", None, -1))

