# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\add_columns_by_formulae.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\add_columns_by_formulae.ui' applies.
#
# Created: Sat Mar  5 14:42:49 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddColumnsByFormulaeDialog(object):
    def setupUi(self, AddColumnsByFormulaeDialog):
        AddColumnsByFormulaeDialog.setObjectName("AddColumnsByFormulaeDialog")
        AddColumnsByFormulaeDialog.resize(464, 300)
        self.gridLayout = QtWidgets.QGridLayout(AddColumnsByFormulaeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tblAlias = QtWidgets.QTableWidget(AddColumnsByFormulaeDialog)
        self.tblAlias.setAlternatingRowColors(True)
        self.tblAlias.setObjectName("tblAlias")
        self.tblAlias.setColumnCount(0)
        self.tblAlias.setRowCount(0)
        self.tblAlias.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tblAlias, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(AddColumnsByFormulaeDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.tblMappings = QtWidgets.QTableWidget(AddColumnsByFormulaeDialog)
        self.tblMappings.setAlternatingRowColors(True)
        self.tblMappings.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblMappings.setObjectName("tblMappings")
        self.tblMappings.setColumnCount(0)
        self.tblMappings.setRowCount(0)
        self.gridLayout.addWidget(self.tblMappings, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btLoadMappings = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btLoadMappings.setIcon(icon)
        self.btLoadMappings.setObjectName("btLoadMappings")
        self.horizontalLayout.addWidget(self.btLoadMappings)
        self.btSaveMappings = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSaveMappings.setIcon(icon1)
        self.btSaveMappings.setObjectName("btSaveMappings")
        self.horizontalLayout.addWidget(self.btSaveMappings)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(AddColumnsByFormulaeDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btAddMapping = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddMapping.setIcon(icon2)
        self.btAddMapping.setObjectName("btAddMapping")
        self.verticalLayout.addWidget(self.btAddMapping)
        self.btRemoveMappings = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveMappings.setIcon(icon3)
        self.btRemoveMappings.setObjectName("btRemoveMappings")
        self.verticalLayout.addWidget(self.btRemoveMappings)
        self.line = QtWidgets.QFrame(AddColumnsByFormulaeDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btAddFunction = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/sigma.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddFunction.setIcon(icon4)
        self.btAddFunction.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btAddFunction.setObjectName("btAddFunction")
        self.verticalLayout.addWidget(self.btAddFunction)
        self.btAddConstant = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/pi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddConstant.setIcon(icon5)
        self.btAddConstant.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btAddConstant.setObjectName("btAddConstant")
        self.verticalLayout.addWidget(self.btAddConstant)
        self.btAddOperator = QtWidgets.QToolButton(AddColumnsByFormulaeDialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/operator.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddOperator.setIcon(icon6)
        self.btAddOperator.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btAddOperator.setObjectName("btAddOperator")
        self.verticalLayout.addWidget(self.btAddOperator)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 2, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddColumnsByFormulaeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 1, 1, 2)

        self.retranslateUi(AddColumnsByFormulaeDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AddColumnsByFormulaeDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AddColumnsByFormulaeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddColumnsByFormulaeDialog)

    def retranslateUi(self, AddColumnsByFormulaeDialog):
        AddColumnsByFormulaeDialog.setWindowTitle(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Columns By Formulae", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Available Columns", None, -1))
        self.tblMappings.setSortingEnabled(True)
        self.btLoadMappings.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Load mapping from a file", None, -1))
        self.btLoadMappings.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Load mapping from a file", None, -1))
        self.btLoadMappings.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "&Load", None, -1))
        self.btSaveMappings.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Save mapping to a file", None, -1))
        self.btSaveMappings.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Save mapping to a file", None, -1))
        self.btSaveMappings.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "&Save", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Mappings", None, -1))
        self.btAddMapping.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add a new mapping at the end of the list", None, -1))
        self.btAddMapping.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add a new mapping at the end of the list", None, -1))
        self.btAddMapping.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "+", None, -1))
        self.btRemoveMappings.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Remove selected mappings from the list", None, -1))
        self.btRemoveMappings.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Remove selected mappings from the list", None, -1))
        self.btRemoveMappings.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "-", None, -1))
        self.btAddFunction.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Function", None, -1))
        self.btAddFunction.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Function", None, -1))
        self.btAddFunction.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "...", None, -1))
        self.btAddConstant.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Constant", None, -1))
        self.btAddConstant.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Constant", None, -1))
        self.btAddConstant.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "...", None, -1))
        self.btAddOperator.setToolTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Operator", None, -1))
        self.btAddOperator.setStatusTip(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "Add Operator", None, -1))
        self.btAddOperator.setText(QtWidgets.QApplication.translate("AddColumnsByFormulaeDialog", "...", None, -1))

import ui_rc
