# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\color_mapping_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\color_mapping_dialog.ui' applies.
#
# Created: Sat Mar  5 14:42:50 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ColorMappingDialog(object):
    def setupUi(self, ColorMappingDialog):
        ColorMappingDialog.setObjectName("ColorMappingDialog")
        ColorMappingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ColorMappingDialog.resize(897, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/main.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ColorMappingDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ColorMappingDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ColorMappingDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 9, 1, 1)
        self.lstColumns = QtWidgets.QListWidget(ColorMappingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstColumns.sizePolicy().hasHeightForWidth())
        self.lstColumns.setSizePolicy(sizePolicy)
        self.lstColumns.setBaseSize(QtCore.QSize(256, 0))
        self.lstColumns.setProperty("showDropIndicator", False)
        self.lstColumns.setDragEnabled(True)
        self.lstColumns.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstColumns.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstColumns.setAlternatingRowColors(True)
        self.lstColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstColumns.setUniformItemSizes(True)
        self.lstColumns.setObjectName("lstColumns")
        self.gridLayout.addWidget(self.lstColumns, 2, 0, 1, 3)
        self.layoutSelectedColumns = QtWidgets.QVBoxLayout()
        self.layoutSelectedColumns.setObjectName("layoutSelectedColumns")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutSelectedColumns.addItem(spacerItem)
        self.btUseSelectedColumns = QtWidgets.QToolButton(ColorMappingDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/go-next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btUseSelectedColumns.setIcon(icon1)
        self.btUseSelectedColumns.setObjectName("btUseSelectedColumns")
        self.layoutSelectedColumns.addWidget(self.btUseSelectedColumns)
        self.btRemoveSelectedColumns = QtWidgets.QToolButton(ColorMappingDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/go-previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveSelectedColumns.setIcon(icon2)
        self.btRemoveSelectedColumns.setObjectName("btRemoveSelectedColumns")
        self.layoutSelectedColumns.addWidget(self.btRemoveSelectedColumns)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutSelectedColumns.addItem(spacerItem1)
        self.gridLayout.addLayout(self.layoutSelectedColumns, 2, 4, 1, 1)
        self.lblColumns = QtWidgets.QLabel(ColorMappingDialog)
        self.lblColumns.setObjectName("lblColumns")
        self.gridLayout.addWidget(self.lblColumns, 0, 0, 1, 3)
        self.lstUsedColumns = QtWidgets.QListWidget(ColorMappingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstUsedColumns.sizePolicy().hasHeightForWidth())
        self.lstUsedColumns.setSizePolicy(sizePolicy)
        self.lstUsedColumns.setBaseSize(QtCore.QSize(256, 0))
        self.lstUsedColumns.setProperty("showDropIndicator", False)
        self.lstUsedColumns.setDragEnabled(True)
        self.lstUsedColumns.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstUsedColumns.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstUsedColumns.setAlternatingRowColors(True)
        self.lstUsedColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstUsedColumns.setIconSize(QtCore.QSize(32, 32))
        self.lstUsedColumns.setUniformItemSizes(True)
        self.lstUsedColumns.setObjectName("lstUsedColumns")
        self.gridLayout.addWidget(self.lstUsedColumns, 2, 5, 1, 2)
        self.btGenerateColors = QtWidgets.QToolButton(ColorMappingDialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/magic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btGenerateColors.setIcon(icon3)
        self.btGenerateColors.setObjectName("btGenerateColors")
        self.gridLayout.addWidget(self.btGenerateColors, 0, 11, 1, 1)
        self.cbColorMap = QtWidgets.QComboBox(ColorMappingDialog)
        self.cbColorMap.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cbColorMap.setIconSize(QtCore.QSize(48, 16))
        self.cbColorMap.setObjectName("cbColorMap")
        self.gridLayout.addWidget(self.cbColorMap, 0, 10, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btEditColor = QtWidgets.QToolButton(ColorMappingDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/pencil.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btEditColor.setIcon(icon4)
        self.btEditColor.setObjectName("btEditColor")
        self.verticalLayout.addWidget(self.btEditColor)
        self.btAddColor = QtWidgets.QToolButton(ColorMappingDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddColor.setIcon(icon5)
        self.btAddColor.setObjectName("btAddColor")
        self.verticalLayout.addWidget(self.btAddColor)
        self.btRemoveColors = QtWidgets.QToolButton(ColorMappingDialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveColors.setIcon(icon6)
        self.btRemoveColors.setObjectName("btRemoveColors")
        self.verticalLayout.addWidget(self.btRemoveColors)
        self.line_2 = QtWidgets.QFrame(ColorMappingDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btLoadColorList = QtWidgets.QToolButton(ColorMappingDialog)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btLoadColorList.setIcon(icon7)
        self.btLoadColorList.setObjectName("btLoadColorList")
        self.verticalLayout.addWidget(self.btLoadColorList)
        self.btSaveColorList = QtWidgets.QToolButton(ColorMappingDialog)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSaveColorList.setIcon(icon8)
        self.btSaveColorList.setObjectName("btSaveColorList")
        self.verticalLayout.addWidget(self.btSaveColorList)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout, 2, 11, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.btAutoAssignColors = QtWidgets.QToolButton(ColorMappingDialog)
        self.btAutoAssignColors.setIcon(icon2)
        self.btAutoAssignColors.setObjectName("btAutoAssignColors")
        self.verticalLayout_3.addWidget(self.btAutoAssignColors)
        self.btRemoveSelectedColumnsColors = QtWidgets.QToolButton(ColorMappingDialog)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveSelectedColumnsColors.setIcon(icon9)
        self.btRemoveSelectedColumnsColors.setObjectName("btRemoveSelectedColumnsColors")
        self.verticalLayout_3.addWidget(self.btRemoveSelectedColumnsColors)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 7, 1, 1)
        self.lstColors = QtWidgets.QListWidget(ColorMappingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstColors.sizePolicy().hasHeightForWidth())
        self.lstColors.setSizePolicy(sizePolicy)
        self.lstColors.setBaseSize(QtCore.QSize(256, 0))
        self.lstColors.setProperty("showDropIndicator", False)
        self.lstColors.setDragEnabled(True)
        self.lstColors.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.lstColors.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.lstColors.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstColors.setIconSize(QtCore.QSize(32, 32))
        self.lstColors.setUniformItemSizes(True)
        self.lstColors.setObjectName("lstColors")
        self.gridLayout.addWidget(self.lstColors, 2, 9, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ColorMappingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 4, 1, 8)
        self.layoutBins = QtWidgets.QHBoxLayout()
        self.layoutBins.setObjectName("layoutBins")
        self.lblUsedColumns = QtWidgets.QLabel(ColorMappingDialog)
        self.lblUsedColumns.setObjectName("lblUsedColumns")
        self.layoutBins.addWidget(self.lblUsedColumns)
        self.btGenerateBins = QtWidgets.QToolButton(ColorMappingDialog)
        self.btGenerateBins.setIcon(icon3)
        self.btGenerateBins.setObjectName("btGenerateBins")
        self.layoutBins.addWidget(self.btGenerateBins)
        self.line = QtWidgets.QFrame(ColorMappingDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutBins.addWidget(self.line)
        self.btMergeBins = QtWidgets.QToolButton(ColorMappingDialog)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/merge.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btMergeBins.setIcon(icon10)
        self.btMergeBins.setObjectName("btMergeBins")
        self.layoutBins.addWidget(self.btMergeBins)
        self.btSplitBins = QtWidgets.QToolButton(ColorMappingDialog)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/images/split.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSplitBins.setIcon(icon11)
        self.btSplitBins.setObjectName("btSplitBins")
        self.layoutBins.addWidget(self.btSplitBins)
        self.line_3 = QtWidgets.QFrame(ColorMappingDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutBins.addWidget(self.line_3)
        self.btEditBin = QtWidgets.QToolButton(ColorMappingDialog)
        self.btEditBin.setIcon(icon4)
        self.btEditBin.setObjectName("btEditBin")
        self.layoutBins.addWidget(self.btEditBin)
        self.btAddBin = QtWidgets.QToolButton(ColorMappingDialog)
        self.btAddBin.setIcon(icon5)
        self.btAddBin.setObjectName("btAddBin")
        self.layoutBins.addWidget(self.btAddBin)
        self.btRemoveBins = QtWidgets.QToolButton(ColorMappingDialog)
        self.btRemoveBins.setIcon(icon6)
        self.btRemoveBins.setObjectName("btRemoveBins")
        self.layoutBins.addWidget(self.btRemoveBins)
        self.gridLayout.addLayout(self.layoutBins, 0, 5, 1, 2)

        self.retranslateUi(ColorMappingDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ColorMappingDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ColorMappingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ColorMappingDialog)

    def retranslateUi(self, ColorMappingDialog):
        ColorMappingDialog.setWindowTitle(QtWidgets.QApplication.translate("ColorMappingDialog", "Add Color Mapping", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "Available colors", None, -1))
        self.lstColumns.setSortingEnabled(True)
        self.btUseSelectedColumns.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Use selected columns", None, -1))
        self.btUseSelectedColumns.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Use selected columns", None, -1))
        self.btUseSelectedColumns.setText(QtWidgets.QApplication.translate("ColorMappingDialog", ">", None, -1))
        self.btRemoveSelectedColumns.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected columns", None, -1))
        self.btRemoveSelectedColumns.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected columns", None, -1))
        self.btRemoveSelectedColumns.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "<", None, -1))
        self.lblColumns.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "Available columns", None, -1))
        self.lstUsedColumns.setSortingEnabled(True)
        self.btGenerateColors.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Clear the color list and fill it with randomly generated colors", None, -1))
        self.btGenerateColors.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Clear the color list and fill it with randomly generated colors", None, -1))
        self.btGenerateColors.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Generate colors", None, -1))
        self.btEditColor.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Change selected color", None, -1))
        self.btEditColor.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Change selected color", None, -1))
        self.btEditColor.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Edit", None, -1))
        self.btAddColor.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Add a new color at the end of the list", None, -1))
        self.btAddColor.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Add a new color at the end of the list", None, -1))
        self.btAddColor.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "+", None, -1))
        self.btRemoveColors.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected colors from the list", None, -1))
        self.btRemoveColors.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected colors from the list", None, -1))
        self.btRemoveColors.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "-", None, -1))
        self.btLoadColorList.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Open a color list", None, -1))
        self.btLoadColorList.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Open a color list", None, -1))
        self.btLoadColorList.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Load", None, -1))
        self.btSaveColorList.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Save colors list to a file", None, -1))
        self.btSaveColorList.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Save colors list to a file", None, -1))
        self.btSaveColorList.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Save", None, -1))
        self.btAutoAssignColors.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Assign colors automatically", None, -1))
        self.btAutoAssignColors.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Assign colors automatically", None, -1))
        self.btAutoAssignColors.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "<", None, -1))
        self.btRemoveSelectedColumnsColors.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove colors from selected columns", None, -1))
        self.btRemoveSelectedColumnsColors.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove colors from selected columns", None, -1))
        self.btRemoveSelectedColumnsColors.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Remove", None, -1))
        self.lblUsedColumns.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "Columns", None, -1))
        self.btGenerateBins.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Generate a user defined number of bins", None, -1))
        self.btGenerateBins.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Generate a user defined number of bins", None, -1))
        self.btGenerateBins.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Generate bins", None, -1))
        self.btMergeBins.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Merge selected bins", None, -1))
        self.btMergeBins.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Merge selected bins", None, -1))
        self.btMergeBins.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Merge bins", None, -1))
        self.btSplitBins.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Split selected bins in two", None, -1))
        self.btSplitBins.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Split selected bins in two", None, -1))
        self.btSplitBins.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Split bins", None, -1))
        self.btEditBin.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Edit selected bin", None, -1))
        self.btEditBin.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Edit selected bin", None, -1))
        self.btEditBin.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "&Edit bin", None, -1))
        self.btAddBin.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Add a new bin at the end of the list", None, -1))
        self.btAddBin.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Add a new bin at the end of the list", None, -1))
        self.btAddBin.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "+", None, -1))
        self.btRemoveBins.setToolTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected bins from the list", None, -1))
        self.btRemoveBins.setStatusTip(QtWidgets.QApplication.translate("ColorMappingDialog", "Remove selected bins from the list", None, -1))
        self.btRemoveBins.setText(QtWidgets.QApplication.translate("ColorMappingDialog", "-", None, -1))

import ui_rc
