# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\import_metadata_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\import_metadata_dialog.ui' applies.
#
# Created: Sat Mar  5 14:42:52 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ImportMetadataDialog(object):
    def setupUi(self, ImportMetadataDialog):
        ImportMetadataDialog.setObjectName("ImportMetadataDialog")
        ImportMetadataDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ImportMetadataDialog.resize(725, 481)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportMetadataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.editMetadataFile = QtWidgets.QLineEdit(ImportMetadataDialog)
        self.editMetadataFile.setEnabled(True)
        self.editMetadataFile.setMinimumSize(QtCore.QSize(200, 0))
        self.editMetadataFile.setObjectName("editMetadataFile")
        self.horizontalLayout_3.addWidget(self.editMetadataFile)
        self.btBrowseMetadataFile = QtWidgets.QPushButton(ImportMetadataDialog)
        self.btBrowseMetadataFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btBrowseMetadataFile.sizePolicy().hasHeightForWidth())
        self.btBrowseMetadataFile.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/folder-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btBrowseMetadataFile.setIcon(icon)
        self.btBrowseMetadataFile.setObjectName("btBrowseMetadataFile")
        self.horizontalLayout_3.addWidget(self.btBrowseMetadataFile)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(ImportMetadataDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 2)
        self.chkUseFirstLineAsHeader = QtWidgets.QCheckBox(self.groupBox)
        self.chkUseFirstLineAsHeader.setObjectName("chkUseFirstLineAsHeader")
        self.gridLayout.addWidget(self.chkUseFirstLineAsHeader, 2, 4, 1, 2)
        self.chkComment = QtWidgets.QCheckBox(self.groupBox)
        self.chkComment.setObjectName("chkComment")
        self.gridLayout.addWidget(self.chkComment, 2, 0, 1, 2)
        self.editComment = QtWidgets.QLineEdit(self.groupBox)
        self.editComment.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editComment.sizePolicy().hasHeightForWidth())
        self.editComment.setSizePolicy(sizePolicy)
        self.editComment.setMaximumSize(QtCore.QSize(37, 16777215))
        self.editComment.setMaxLength(1)
        self.editComment.setObjectName("editComment")
        self.gridLayout.addWidget(self.editComment, 2, 2, 1, 1)
        self.cbCsvDelimiter = CsvDelimiterCombo(self.groupBox)
        self.cbCsvDelimiter.setObjectName("cbCsvDelimiter")
        self.gridLayout.addWidget(self.cbCsvDelimiter, 0, 1, 1, 1)
        self.spinSkipRows = QtWidgets.QSpinBox(self.groupBox)
        self.spinSkipRows.setMinimum(1)
        self.spinSkipRows.setMaximum(2147483647)
        self.spinSkipRows.setObjectName("spinSkipRows")
        self.gridLayout.addWidget(self.spinSkipRows, 0, 5, 1, 1)
        self.editCsvDelimiter = QtWidgets.QLineEdit(self.groupBox)
        self.editCsvDelimiter.setEnabled(False)
        self.editCsvDelimiter.setMaximumSize(QtCore.QSize(37, 16777215))
        self.editCsvDelimiter.setMaxLength(1)
        self.editCsvDelimiter.setObjectName("editCsvDelimiter")
        self.gridLayout.addWidget(self.editCsvDelimiter, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 5, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cbIndexColumn = QtWidgets.QComboBox(self.groupBox)
        self.cbIndexColumn.setObjectName("cbIndexColumn")
        self.gridLayout.addWidget(self.cbIndexColumn, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ImportMetadataDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btSelectAll = QtWidgets.QToolButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/select-all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectAll.setIcon(icon1)
        self.btSelectAll.setObjectName("btSelectAll")
        self.horizontalLayout.addWidget(self.btSelectAll)
        self.btSelectNone = QtWidgets.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/select-none.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectNone.setIcon(icon2)
        self.btSelectNone.setObjectName("btSelectNone")
        self.horizontalLayout.addWidget(self.btSelectNone)
        self.btSelectInvert = QtWidgets.QToolButton(self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/select-invert.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectInvert.setIcon(icon3)
        self.btSelectInvert.setObjectName("btSelectInvert")
        self.horizontalLayout.addWidget(self.btSelectInvert)
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.btRefresh = QtWidgets.QToolButton(self.groupBox_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRefresh.setIcon(icon4)
        self.btRefresh.setObjectName("btRefresh")
        self.horizontalLayout.addWidget(self.btRefresh)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.twMetadata = LoadingTableWidget(self.groupBox_2)
        self.twMetadata.setObjectName("twMetadata")
        self.twMetadata.setColumnCount(0)
        self.twMetadata.setRowCount(0)
        self.verticalLayout_2.addWidget(self.twMetadata)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportMetadataDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportMetadataDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImportMetadataDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImportMetadataDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportMetadataDialog)

    def retranslateUi(self, ImportMetadataDialog):
        ImportMetadataDialog.setWindowTitle(QtWidgets.QApplication.translate("ImportMetadataDialog", "Import metadata", None, -1))
        self.editMetadataFile.setPlaceholderText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Choose a metadata file", None, -1))
        self.btBrowseMetadataFile.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "&Browse...", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ImportMetadataDialog", "Options", None, -1))
        self.chkUseFirstLineAsHeader.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Use first line as column header", None, -1))
        self.chkComment.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Ignore lines starting with", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Separator", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Start import row", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Index column", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("ImportMetadataDialog", "Preview", None, -1))
        self.btSelectAll.setToolTip(QtWidgets.QApplication.translate("ImportMetadataDialog", "Select all items", None, -1))
        self.btSelectAll.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Select &all", None, -1))
        self.btSelectNone.setToolTip(QtWidgets.QApplication.translate("ImportMetadataDialog", "Select nothing", None, -1))
        self.btSelectNone.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "Select &none", None, -1))
        self.btSelectInvert.setToolTip(QtWidgets.QApplication.translate("ImportMetadataDialog", "Invert selection", None, -1))
        self.btSelectInvert.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "&Invert selection", None, -1))
        self.btRefresh.setToolTip(QtWidgets.QApplication.translate("ImportMetadataDialog", "Refresh preview", None, -1))
        self.btRefresh.setText(QtWidgets.QApplication.translate("ImportMetadataDialog", "...", None, -1))

from metgem_app.ui.widgets import LoadingTableWidget, CsvDelimiterCombo
import ui_rc
