# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\plugins_manager_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\plugins_manager_dialog.ui' applies.
#
# Created: Sat Mar  5 14:42:55 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PluginsManager(object):
    def setupUi(self, PluginsManager):
        PluginsManager.setObjectName("PluginsManager")
        PluginsManager.setWindowModality(QtCore.Qt.ApplicationModal)
        PluginsManager.resize(706, 438)
        PluginsManager.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PluginsManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PluginsManager)
        self.tabWidget.setObjectName("tabWidget")
        self.available = QtWidgets.QWidget()
        self.available.setObjectName("available")
        self.gridLayout = QtWidgets.QGridLayout(self.available)
        self.gridLayout.setObjectName("gridLayout")
        self.tvAvailable = QtWidgets.QTableView(self.available)
        self.tvAvailable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvAvailable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvAvailable.setSortingEnabled(True)
        self.tvAvailable.setObjectName("tvAvailable")
        self.gridLayout.addWidget(self.tvAvailable, 3, 0, 1, 5)
        self.lblADescription = QtWidgets.QLabel(self.available)
        self.lblADescription.setText("")
        self.lblADescription.setObjectName("lblADescription")
        self.gridLayout.addWidget(self.lblADescription, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leASearch = QtWidgets.QLineEdit(self.available)
        self.leASearch.setMinimumSize(QtCore.QSize(300, 0))
        self.leASearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leASearch.setBaseSize(QtCore.QSize(0, 0))
        self.leASearch.setObjectName("leASearch")
        self.horizontalLayout.addWidget(self.leASearch)
        self.btASearch = QtWidgets.QToolButton(self.available)
        self.btASearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/system-search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btASearch.setIcon(icon)
        self.btASearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btASearch.setObjectName("btASearch")
        self.horizontalLayout.addWidget(self.btASearch)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.btInstall = QtWidgets.QToolButton(self.available)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/install.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btInstall.setIcon(icon1)
        self.btInstall.setIconSize(QtCore.QSize(24, 24))
        self.btInstall.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btInstall.setObjectName("btInstall")
        self.gridLayout.addWidget(self.btInstall, 5, 4, 1, 1)
        self.tabWidget.addTab(self.available, "")
        self.updates = QtWidgets.QWidget()
        self.updates.setObjectName("updates")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.updates)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btUpdate = QtWidgets.QToolButton(self.updates)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/update.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btUpdate.setIcon(icon2)
        self.btUpdate.setIconSize(QtCore.QSize(24, 24))
        self.btUpdate.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btUpdate.setObjectName("btUpdate")
        self.gridLayout_2.addWidget(self.btUpdate, 2, 1, 1, 1)
        self.tvUpdates = QtWidgets.QTableView(self.updates)
        self.tvUpdates.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvUpdates.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvUpdates.setSortingEnabled(True)
        self.tvUpdates.setObjectName("tvUpdates")
        self.gridLayout_2.addWidget(self.tvUpdates, 1, 0, 1, 2)
        self.lblUDescription = QtWidgets.QLabel(self.updates)
        self.lblUDescription.setText("")
        self.lblUDescription.setObjectName("lblUDescription")
        self.gridLayout_2.addWidget(self.lblUDescription, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leUSearch = QtWidgets.QLineEdit(self.updates)
        self.leUSearch.setMinimumSize(QtCore.QSize(300, 0))
        self.leUSearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leUSearch.setBaseSize(QtCore.QSize(0, 0))
        self.leUSearch.setObjectName("leUSearch")
        self.horizontalLayout_2.addWidget(self.leUSearch)
        self.btUSearch = QtWidgets.QToolButton(self.updates)
        self.btUSearch.setText("")
        self.btUSearch.setIcon(icon)
        self.btUSearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btUSearch.setObjectName("btUSearch")
        self.horizontalLayout_2.addWidget(self.btUSearch)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.tabWidget.addTab(self.updates, "")
        self.installed = QtWidgets.QWidget()
        self.installed.setObjectName("installed")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.installed)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btUninstall = QtWidgets.QToolButton(self.installed)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/uninstall.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btUninstall.setIcon(icon3)
        self.btUninstall.setIconSize(QtCore.QSize(24, 24))
        self.btUninstall.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btUninstall.setObjectName("btUninstall")
        self.gridLayout_3.addWidget(self.btUninstall, 2, 1, 1, 1)
        self.tvInstalled = QtWidgets.QTableView(self.installed)
        self.tvInstalled.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvInstalled.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvInstalled.setSortingEnabled(True)
        self.tvInstalled.setObjectName("tvInstalled")
        self.gridLayout_3.addWidget(self.tvInstalled, 1, 0, 1, 2)
        self.lblIDescription = QtWidgets.QLabel(self.installed)
        self.lblIDescription.setText("")
        self.lblIDescription.setObjectName("lblIDescription")
        self.gridLayout_3.addWidget(self.lblIDescription, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leISearch = QtWidgets.QLineEdit(self.installed)
        self.leISearch.setMinimumSize(QtCore.QSize(300, 0))
        self.leISearch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leISearch.setBaseSize(QtCore.QSize(0, 0))
        self.leISearch.setObjectName("leISearch")
        self.horizontalLayout_3.addWidget(self.leISearch)
        self.btISearch = QtWidgets.QToolButton(self.installed)
        self.btISearch.setText("")
        self.btISearch.setIcon(icon)
        self.btISearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btISearch.setObjectName("btISearch")
        self.horizontalLayout_3.addWidget(self.btISearch)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.tabWidget.addTab(self.installed, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PluginsManager)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PluginsManager)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PluginsManager.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PluginsManager.reject)
        QtCore.QMetaObject.connectSlotsByName(PluginsManager)

    def retranslateUi(self, PluginsManager):
        PluginsManager.setWindowTitle(QtWidgets.QApplication.translate("PluginsManager", "PluginsManager", None, -1))
        self.leASearch.setPlaceholderText(QtWidgets.QApplication.translate("PluginsManager", "Search", None, -1))
        self.btInstall.setText(QtWidgets.QApplication.translate("PluginsManager", "Install", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.available), QtWidgets.QApplication.translate("PluginsManager", "Available", None, -1))
        self.btUpdate.setText(QtWidgets.QApplication.translate("PluginsManager", "Update", None, -1))
        self.leUSearch.setPlaceholderText(QtWidgets.QApplication.translate("PluginsManager", "Search", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updates), QtWidgets.QApplication.translate("PluginsManager", "Updates", None, -1))
        self.btUninstall.setText(QtWidgets.QApplication.translate("PluginsManager", "Uninstall", None, -1))
        self.leISearch.setPlaceholderText(QtWidgets.QApplication.translate("PluginsManager", "Search", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.installed), QtWidgets.QApplication.translate("PluginsManager", "Installed", None, -1))

import ui_rc
