# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\process_data_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\process_data_dialog.ui' applies.
#
# Created: Sat Mar  5 14:42:56 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ProcessFileDialog(object):
    def setupUi(self, ProcessFileDialog):
        ProcessFileDialog.setObjectName("ProcessFileDialog")
        ProcessFileDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProcessFileDialog.resize(712, 411)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProcessFileDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(ProcessFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.gbMetadata = QtWidgets.QGroupBox(ProcessFileDialog)
        self.gbMetadata.setCheckable(True)
        self.gbMetadata.setChecked(True)
        self.gbMetadata.setObjectName("gbMetadata")
        self.gridLayout = QtWidgets.QGridLayout(self.gbMetadata)
        self.gridLayout.setObjectName("gridLayout")
        self.btBrowseMetadataFile = QtWidgets.QPushButton(self.gbMetadata)
        self.btBrowseMetadataFile.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/folder-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btBrowseMetadataFile.setIcon(icon)
        self.btBrowseMetadataFile.setObjectName("btBrowseMetadataFile")
        self.gridLayout.addWidget(self.btBrowseMetadataFile, 0, 1, 1, 1)
        self.btOptions = QtWidgets.QToolButton(self.gbMetadata)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/preferences-system.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btOptions.setIcon(icon1)
        self.btOptions.setObjectName("btOptions")
        self.gridLayout.addWidget(self.btOptions, 0, 2, 1, 1)
        self.editMetadataFile = QtWidgets.QLineEdit(self.gbMetadata)
        self.editMetadataFile.setEnabled(True)
        self.editMetadataFile.setMinimumSize(QtCore.QSize(200, 0))
        self.editMetadataFile.setObjectName("editMetadataFile")
        self.gridLayout.addWidget(self.editMetadataFile, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbMetadata, 1, 0, 1, 1)
        self.gbProcess = QtWidgets.QGroupBox(ProcessFileDialog)
        self.gbProcess.setObjectName("gbProcess")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbProcess)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.editProcessFile = QtWidgets.QLineEdit(self.gbProcess)
        self.editProcessFile.setMinimumSize(QtCore.QSize(200, 0))
        self.editProcessFile.setObjectName("editProcessFile")
        self.horizontalLayout_4.addWidget(self.editProcessFile)
        self.btBrowseProcessFile = QtWidgets.QPushButton(self.gbProcess)
        self.btBrowseProcessFile.setIcon(icon)
        self.btBrowseProcessFile.setObjectName("btBrowseProcessFile")
        self.horizontalLayout_4.addWidget(self.btBrowseProcessFile)
        self.gridLayout_2.addWidget(self.gbProcess, 0, 0, 1, 1)
        self.gbAddViews = QtWidgets.QGroupBox(ProcessFileDialog)
        self.gbAddViews.setObjectName("gbAddViews")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbAddViews)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lstViews = QtWidgets.QListWidget(self.gbAddViews)
        self.lstViews.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.lstViews.setAlternatingRowColors(True)
        self.lstViews.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstViews.setUniformItemSizes(True)
        self.lstViews.setObjectName("lstViews")
        self.horizontalLayout_3.addWidget(self.lstViews)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btAddView = QtWidgets.QToolButton(self.gbAddViews)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddView.setIcon(icon2)
        self.btAddView.setIconSize(QtCore.QSize(16, 16))
        self.btAddView.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btAddView.setObjectName("btAddView")
        self.verticalLayout.addWidget(self.btAddView)
        self.btRemoveViews = QtWidgets.QPushButton(self.gbAddViews)
        self.btRemoveViews.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveViews.setIcon(icon3)
        self.btRemoveViews.setObjectName("btRemoveViews")
        self.verticalLayout.addWidget(self.btRemoveViews)
        self.btEditView = QtWidgets.QPushButton(self.gbAddViews)
        self.btEditView.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/list-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btEditView.setIcon(icon4)
        self.btEditView.setObjectName("btEditView")
        self.verticalLayout.addWidget(self.btEditView)
        self.btClear = QtWidgets.QPushButton(self.gbAddViews)
        self.btClear.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/list-clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btClear.setIcon(icon5)
        self.btClear.setObjectName("btClear")
        self.verticalLayout.addWidget(self.btClear)
        self.line = QtWidgets.QFrame(self.gbAddViews)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btSelectAll = QtWidgets.QPushButton(self.gbAddViews)
        self.btSelectAll.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/select-all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectAll.setIcon(icon6)
        self.btSelectAll.setObjectName("btSelectAll")
        self.verticalLayout.addWidget(self.btSelectAll)
        self.btSelectNone = QtWidgets.QPushButton(self.gbAddViews)
        self.btSelectNone.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/select-none.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectNone.setIcon(icon7)
        self.btSelectNone.setObjectName("btSelectNone")
        self.verticalLayout.addWidget(self.btSelectNone)
        self.btSelectInvert = QtWidgets.QPushButton(self.gbAddViews)
        self.btSelectInvert.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/select-invert.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSelectInvert.setIcon(icon8)
        self.btSelectInvert.setObjectName("btSelectInvert")
        self.verticalLayout.addWidget(self.btSelectInvert)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.gbAddViews, 0, 3, 3, 1)

        self.retranslateUi(ProcessFileDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ProcessFileDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ProcessFileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProcessFileDialog)

    def retranslateUi(self, ProcessFileDialog):
        ProcessFileDialog.setWindowTitle(QtWidgets.QApplication.translate("ProcessFileDialog", "Process File", None, -1))
        self.gbMetadata.setTitle(QtWidgets.QApplication.translate("ProcessFileDialog", "Metadata", None, -1))
        self.btBrowseMetadataFile.setText(QtWidgets.QApplication.translate("ProcessFileDialog", "&Browse...", None, -1))
        self.btOptions.setText(QtWidgets.QApplication.translate("ProcessFileDialog", "Options...", None, -1))
        self.editMetadataFile.setPlaceholderText(QtWidgets.QApplication.translate("ProcessFileDialog", "Choose a metadata file", None, -1))
        self.gbProcess.setTitle(QtWidgets.QApplication.translate("ProcessFileDialog", "File to process", None, -1))
        self.editProcessFile.setPlaceholderText(QtWidgets.QApplication.translate("ProcessFileDialog", "Choose a data file to import", None, -1))
        self.btBrowseProcessFile.setText(QtWidgets.QApplication.translate("ProcessFileDialog", "&Browse...", None, -1))
        self.gbAddViews.setTitle(QtWidgets.QApplication.translate("ProcessFileDialog", "Add Views", None, -1))
        self.btAddView.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Add a view to the list", None, -1))
        self.btAddView.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Add a view to the list", None, -1))
        self.btAddView.setText(QtWidgets.QApplication.translate("ProcessFileDialog", "&Add", None, -1))
        self.btRemoveViews.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Remove selected view(s) from the list", None, -1))
        self.btRemoveViews.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Remove selected view(s) from the list", None, -1))
        self.btEditView.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Edit selected view options", None, -1))
        self.btEditView.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Edit selected view options", None, -1))
        self.btClear.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Clear list", None, -1))
        self.btClear.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Clear list", None, -1))
        self.btSelectAll.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Select all items", None, -1))
        self.btSelectAll.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Select all items", None, -1))
        self.btSelectNone.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Select nothing", None, -1))
        self.btSelectNone.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Select nothing", None, -1))
        self.btSelectInvert.setToolTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Invert selection", None, -1))
        self.btSelectInvert.setStatusTip(QtWidgets.QApplication.translate("ProcessFileDialog", "Invert selection", None, -1))

import ui_rc
