# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\size_mapping_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\size_mapping_dialog.ui' applies.
#
# Created: Sat Mar  5 14:42:59 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(680, 546)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/main.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gvMapping = QtWidgets.QGraphicsView(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gvMapping.sizePolicy().hasHeightForWidth())
        self.gvMapping.setSizePolicy(sizePolicy)
        self.gvMapping.setMinimumSize(QtCore.QSize(400, 200))
        self.gvMapping.setMaximumSize(QtCore.QSize(400, 200))
        self.gvMapping.setBaseSize(QtCore.QSize(400, 200))
        self.gvMapping.setObjectName("gvMapping")
        self.gridLayout_2.addWidget(self.gvMapping, 1, 1, 1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 6, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinMinSize = QtWidgets.QSpinBox(self.groupBox)
        self.spinMinSize.setMinimum(10)
        self.spinMinSize.setMaximum(100)
        self.spinMinSize.setObjectName("spinMinSize")
        self.horizontalLayout_2.addWidget(self.spinMinSize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinMaxSize = QtWidgets.QSpinBox(self.groupBox)
        self.spinMaxSize.setMinimum(10)
        self.spinMaxSize.setMaximum(100)
        self.spinMaxSize.setObjectName("spinMaxSize")
        self.horizontalLayout_2.addWidget(self.spinMaxSize)
        self.gridLayout_2.addWidget(self.groupBox, 4, 1, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinHandleSize = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinHandleSize.setEnabled(True)
        self.spinHandleSize.setObjectName("spinHandleSize")
        self.gridLayout.addWidget(self.spinHandleSize, 1, 1, 1, 1)
        self.btAddHandle = QtWidgets.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/list-add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btAddHandle.setIcon(icon1)
        self.btAddHandle.setObjectName("btAddHandle")
        self.gridLayout.addWidget(self.btAddHandle, 0, 3, 1, 1)
        self.btRemoveHandle = QtWidgets.QPushButton(self.groupBox_3)
        self.btRemoveHandle.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRemoveHandle.setIcon(icon2)
        self.btRemoveHandle.setObjectName("btRemoveHandle")
        self.gridLayout.addWidget(self.btRemoveHandle, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.spinHandleValue = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinHandleValue.setEnabled(True)
        self.spinHandleValue.setDecimals(1)
        self.spinHandleValue.setObjectName("spinHandleValue")
        self.gridLayout.addWidget(self.spinHandleValue, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 5, 1, 1, 4)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 1, 1, 1)
        self.cbMode = QtWidgets.QComboBox(Dialog)
        self.cbMode.setObjectName("cbMode")
        self.gridLayout_2.addWidget(self.cbMode, 6, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinMinValue = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinMinValue.setDecimals(1)
        self.spinMinValue.setObjectName("spinMinValue")
        self.horizontalLayout_4.addWidget(self.spinMinValue)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinMaxValue = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinMaxValue.setDecimals(1)
        self.spinMaxValue.setObjectName("spinMaxValue")
        self.horizontalLayout_4.addWidget(self.spinMaxValue)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 1, 1, 4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lstColumns = QtWidgets.QListWidget(Dialog)
        self.lstColumns.setProperty("showDropIndicator", False)
        self.lstColumns.setAlternatingRowColors(True)
        self.lstColumns.setUniformItemSizes(True)
        self.lstColumns.setObjectName("lstColumns")
        self.verticalLayout.addWidget(self.lstColumns)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 6, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Add Size Mapping", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Nodes size", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Min.", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Max.", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Dialog", "Edit Handles Positions", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Node Size", None, -1))
        self.btAddHandle.setToolTip(QtWidgets.QApplication.translate("Dialog", "Add a new handle at specified position", None, -1))
        self.btAddHandle.setStatusTip(QtWidgets.QApplication.translate("Dialog", "Add a new handle at specified position", None, -1))
        self.btAddHandle.setText(QtWidgets.QApplication.translate("Dialog", "Add", None, -1))
        self.btRemoveHandle.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Value", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Mode", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Values", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Min.", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Max.", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Available columns", None, -1))
        self.lstColumns.setSortingEnabled(True)

import ui_rc
