# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\view_databases_dialog.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\view_databases_dialog.ui' applies.
#
# Created: Sat Mar  5 14:43:00 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(923, 532)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btFirst = QtWidgets.QToolButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/go-first.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btFirst.setIcon(icon)
        self.btFirst.setObjectName("btFirst")
        self.horizontalLayout.addWidget(self.btFirst)
        self.btPrevious = QtWidgets.QToolButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/go-previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btPrevious.setIcon(icon1)
        self.btPrevious.setObjectName("btPrevious")
        self.horizontalLayout.addWidget(self.btPrevious)
        self.lblOffset = QtWidgets.QLabel(Dialog)
        self.lblOffset.setMinimumSize(QtCore.QSize(100, 0))
        self.lblOffset.setText("")
        self.lblOffset.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOffset.setObjectName("lblOffset")
        self.horizontalLayout.addWidget(self.lblOffset)
        self.btNext = QtWidgets.QToolButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/go-next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btNext.setIcon(icon2)
        self.btNext.setObjectName("btNext")
        self.horizontalLayout.addWidget(self.btNext)
        self.btLast = QtWidgets.QToolButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/go-last.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btLast.setIcon(icon3)
        self.btLast.setObjectName("btLast")
        self.horizontalLayout.addWidget(self.btLast)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.editGoTo = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editGoTo.sizePolicy().hasHeightForWidth())
        self.editGoTo.setSizePolicy(sizePolicy)
        self.editGoTo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.editGoTo.setClearButtonEnabled(True)
        self.editGoTo.setObjectName("editGoTo")
        self.horizontalLayout.addWidget(self.editGoTo)
        self.btGoTo = QtWidgets.QToolButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/go-jump.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btGoTo.setIcon(icon4)
        self.btGoTo.setObjectName("btGoTo")
        self.horizontalLayout.addWidget(self.btGoTo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbBanks = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBanks.sizePolicy().hasHeightForWidth())
        self.cbBanks.setSizePolicy(sizePolicy)
        self.cbBanks.setMinimumSize(QtCore.QSize(200, 0))
        self.cbBanks.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cbBanks.setObjectName("cbBanks")
        self.horizontalLayout.addWidget(self.cbBanks)
        self.btRefresh = QtWidgets.QToolButton(Dialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btRefresh.setIcon(icon5)
        self.btRefresh.setObjectName("btRefresh")
        self.horizontalLayout.addWidget(self.btRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tvSpectra = QtWidgets.QTableView(self.splitter)
        self.tvSpectra.setAlternatingRowColors(True)
        self.tvSpectra.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvSpectra.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvSpectra.setObjectName("tvSpectra")
        self.widgetSpectrumDetails = SpectrumDetailsWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSpectrumDetails.sizePolicy().hasHeightForWidth())
        self.widgetSpectrumDetails.setSizePolicy(sizePolicy)
        self.widgetSpectrumDetails.setObjectName("widgetSpectrumDetails")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetSpectrumDetails)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btFirst, self.btPrevious)
        Dialog.setTabOrder(self.btPrevious, self.btNext)
        Dialog.setTabOrder(self.btNext, self.btLast)
        Dialog.setTabOrder(self.btLast, self.editGoTo)
        Dialog.setTabOrder(self.editGoTo, self.btGoTo)
        Dialog.setTabOrder(self.btGoTo, self.cbBanks)
        Dialog.setTabOrder(self.cbBanks, self.btRefresh)
        Dialog.setTabOrder(self.btRefresh, self.tvSpectra)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Spectra databases", None, -1))
        self.btFirst.setText(QtWidgets.QApplication.translate("Dialog", "<<", None, -1))
        self.btPrevious.setText(QtWidgets.QApplication.translate("Dialog", "<", None, -1))
        self.btNext.setText(QtWidgets.QApplication.translate("Dialog", ">", None, -1))
        self.btLast.setText(QtWidgets.QApplication.translate("Dialog", ">>", None, -1))
        self.btGoTo.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Database", None, -1))
        self.btRefresh.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))

from metgem_app.ui.widgets import SpectrumDetailsWidget
import ui_rc
