# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\git\metgem\metgem_app\ui\widgets\databases\databases_details.ui',
# licensing of 'E:\git\metgem\metgem_app\ui\widgets\databases\databases_details.ui' applies.
#
# Created: Sat Mar  5 14:43:08 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DownloadDatabaseDialog(object):
    def setupUi(self, DownloadDatabaseDialog):
        DownloadDatabaseDialog.setObjectName("DownloadDatabaseDialog")
        DownloadDatabaseDialog.resize(840, 490)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadDatabaseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(DownloadDatabaseDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgetSpectrum = SpectrumWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSpectrum.sizePolicy().hasHeightForWidth())
        self.widgetSpectrum.setSizePolicy(sizePolicy)
        self.widgetSpectrum.setMinimumSize(QtCore.QSize(300, 272))
        self.widgetSpectrum.setMaximumSize(QtCore.QSize(300, 272))
        self.widgetSpectrum.setObjectName("widgetSpectrum")
        self.verticalLayout_4.addWidget(self.widgetSpectrum)
        self.gridLayout_6.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 1)
        self.lblDataCollector = QtWidgets.QLabel(self.tab)
        self.lblDataCollector.setText("")
        self.lblDataCollector.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblDataCollector.setObjectName("lblDataCollector")
        self.gridLayout_3.addWidget(self.lblDataCollector, 7, 1, 1, 1)
        self.lblOrganism = QtWidgets.QLabel(self.tab)
        self.lblOrganism.setText("")
        self.lblOrganism.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblOrganism.setObjectName("lblOrganism")
        self.gridLayout_3.addWidget(self.lblOrganism, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.lblPi = QtWidgets.QLabel(self.tab)
        self.lblPi.setText("")
        self.lblPi.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblPi.setObjectName("lblPi")
        self.gridLayout_3.addWidget(self.lblPi, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 8, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 1)
        self.lblCharge = QtWidgets.QLabel(self.tab)
        self.lblCharge.setText("")
        self.lblCharge.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblCharge.setObjectName("lblCharge")
        self.gridLayout_3.addWidget(self.lblCharge, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.lblSourceInstrument = QtWidgets.QLabel(self.tab)
        self.lblSourceInstrument.setText("")
        self.lblSourceInstrument.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSourceInstrument.setObjectName("lblSourceInstrument")
        self.gridLayout_3.addWidget(self.lblSourceInstrument, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lblSubmitUser = SubmitUserLabel(self.tab)
        self.lblSubmitUser.setText("")
        self.lblSubmitUser.setOpenExternalLinks(True)
        self.lblSubmitUser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSubmitUser.setObjectName("lblSubmitUser")
        self.gridLayout_3.addWidget(self.lblSubmitUser, 8, 1, 1, 1)
        self.lblQuality = QualityLabel(self.tab)
        self.lblQuality.setText("")
        self.lblQuality.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblQuality.setObjectName("lblQuality")
        self.gridLayout_3.addWidget(self.lblQuality, 9, 1, 1, 1)
        self.lblPolarity = QtWidgets.QLabel(self.tab)
        self.lblPolarity.setText("")
        self.lblPolarity.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblPolarity.setObjectName("lblPolarity")
        self.gridLayout_3.addWidget(self.lblPolarity, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.lblMSLevel = QtWidgets.QLabel(self.tab)
        self.lblMSLevel.setText("")
        self.lblMSLevel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblMSLevel.setObjectName("lblMSLevel")
        self.gridLayout_3.addWidget(self.lblMSLevel, 3, 1, 1, 1)
        self.lblPepmass = QtWidgets.QLabel(self.tab)
        self.lblPepmass.setText("")
        self.lblPepmass.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblPepmass.setObjectName("lblPepmass")
        self.gridLayout_3.addWidget(self.lblPepmass, 0, 1, 1, 1)
        self.lblLibraryId = SpectrumIdLabel(self.tab)
        self.lblLibraryId.setText("")
        self.lblLibraryId.setOpenExternalLinks(True)
        self.lblLibraryId.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblLibraryId.setObjectName("lblLibraryId")
        self.gridLayout_3.addWidget(self.lblLibraryId, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 11, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.widgetFragmentsList = FragmentsListWidget(self.tab)
        self.widgetFragmentsList.setObjectName("widgetFragmentsList")
        self.gridLayout_6.addWidget(self.widgetFragmentsList, 1, 0, 1, 2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/spectrum.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblPubMed = PubMedLabel(self.tab_2)
        self.lblPubMed.setText("")
        self.lblPubMed.setTextFormat(QtCore.Qt.RichText)
        self.lblPubMed.setOpenExternalLinks(True)
        self.lblPubMed.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblPubMed.setObjectName("lblPubMed")
        self.gridLayout.addWidget(self.lblPubMed, 3, 1, 1, 1)
        self.widgetStructure = StructureSvgWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetStructure.sizePolicy().hasHeightForWidth())
        self.widgetStructure.setSizePolicy(sizePolicy)
        self.widgetStructure.setMinimumSize(QtCore.QSize(300, 272))
        self.widgetStructure.setMaximumSize(QtCore.QSize(300, 272))
        self.widgetStructure.setObjectName("widgetStructure")
        self.gridLayout.addWidget(self.widgetStructure, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lblName = QtWidgets.QLabel(self.tab_2)
        self.lblName.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lblName.setText("")
        self.lblName.setWordWrap(True)
        self.lblName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.lblInChI = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInChI.sizePolicy().hasHeightForWidth())
        self.lblInChI.setSizePolicy(sizePolicy)
        self.lblInChI.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lblInChI.setText("")
        self.lblInChI.setWordWrap(True)
        self.lblInChI.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblInChI.setObjectName("lblInChI")
        self.gridLayout.addWidget(self.lblInChI, 1, 1, 1, 1)
        self.lblSmiles = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSmiles.sizePolicy().hasHeightForWidth())
        self.lblSmiles.setSizePolicy(sizePolicy)
        self.lblSmiles.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lblSmiles.setText("")
        self.lblSmiles.setWordWrap(True)
        self.lblSmiles.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblSmiles.setObjectName("lblSmiles")
        self.gridLayout.addWidget(self.lblSmiles, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/molecule.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(DownloadDatabaseDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DownloadDatabaseDialog)

    def retranslateUi(self, DownloadDatabaseDialog):
        DownloadDatabaseDialog.setWindowTitle(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Form", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Library Quality", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Organism", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Submit user", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Principal Investigator", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Library id.", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Polarity", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "MSLevel", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "<i>m/z</i> parent", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Source Instrument", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Data Collector", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Charge", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Spectrum", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "SMILES", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "InChI", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("DownloadDatabaseDialog", "PubMed ref.", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("DownloadDatabaseDialog", "Structure", None, -1))

from metgem_app.ui.widgets.databases.widgets import SubmitUserLabel, PubMedLabel, SpectrumIdLabel, QualityLabel
from metgem_app.ui.widgets.structure import StructureSvgWidget
from metgem_app.ui.widgets.spectrum.widget import SpectrumWidget
from metgem_app.ui.widgets.spectrum import FragmentsListWidget
import ui_rc
